### ISSUE TITLE
Need .netstandard target

### ISSUE THREAD

**Issue by klym1** [CarterCommunity/Carter#222]
Currently, I cannot install Carter for one of my lib projects which has target `netstandard2.1`
```
Package Carter 5.0.0-ci130 supports: netcoreapp3.0 (.NETCoreApp,Version=v3.0)
Package restore failed. Rolling back package changes for '...'
```

Using the latest package version from `https://ci.appveyor.com/nuget/carterci`

**Comment by jchannon** [comment]
Hi,

You can use version 4.2.0 for a netstandard2 target.

This won't have the latest features unfortunately because Carter is going to start supporting the LTS versions of ASP.Net Core and as of yesterday that's 3.1. We will release a new version of Carter, probably 5.1 that will target netcoreapp3.1. 5.0 currently targets netcoreapp3.0
