### ISSUE TITLE
How to use multiple authentication types for OpenApi?

### ISSUE THREAD

**Issue by redthing1** [CarterCommunity/Carter#246]
According to Swagger docs: https://swagger.io/docs/specification/authentication/#multiple

A security scheme can require multiple `OpenApiSecurity`. Say I have defined both (in `options.OpenApi.Securities`):
```csharp
{
	"userBearer",
    new OpenApiSecurity {Type = OpenApiSecurityType.http, Scheme = "bearer"}
}, {
	"apikey",
    new OpenApiSecurity {Type = OpenApiSecurityType.apiKey, In = openApiIn.header, Name = "X-Api-Key"}
}
```
How do I specify that I want both securities (logical AND) in `options.OpenApi.GlobalSecurityDefinitions`?

**Comment by jchannon** [comment]
Hi,

In the sample app we show how to add multiple security schemes
https://github.com/CarterCommunity/Carter/blob/master/samples/CarterSample/Startup.cs#L28
and you would specify which scheme to use on your route metadata
https://github.com/CarterCommunity/Carter/blob/master/samples/CarterSample/Features/Actors/OpenApi/GetActors.cs#L24

However, you'll see that is a string and should be a list of string so you
define all possible security schemes so this seems a bug.

We would have to loop over the list here to make the openapi doc write out
the correct data
https://github.com/CarterCommunity/Carter/blob/master/src/Carter/OpenApi/CarterOpenApi.cs#L500

If you'd like to give it a go and send a PR, please feel free to do so
otherwise we'll try and get this fixed at some point.

Thanks

**Comment by jchannon** [comment]
Carter 6 will use ASP.NET Core OpenAPI implementation
