### ISSUE TITLE
`WithGroupName` and `WithDescription` results in that module not being surface in SwaggerUI

### ISSUE THREAD

**Issue by tdashworth** [CarterCommunity/Carter#317]

**Comment by jchannon** [comment]
Must be a bug in aspnet core or in swagger ui

**Comment by tdashworth** [comment]
Just tested, it seems so 😞 

```csharp
RouteGroupBuilder group = app.MapGroup("/test-group");
group.WithGroupName("test_group").WithDescription("test description"); // Comment this out and it works
group.MapGet("/test", () => "Test");
```

FYI, I am using .NET7

**Comment by Tungsten78** [comment]
Add `.WithOpenApi()` to the group.

**Comment by jchannon** [comment]
Does IncludeInOpenApi() work?

**Comment by alexalok** [comment]
@tdashworth I just spent some time figuring out the same issue. Turns out you should use `WithTags("test_group")` because `WithGroupName` actually lets you select which API definition your requests should be shown for. Since that definition defaults to the name of an entry assembly, `WithGroupName("test_group")` implicitly hid your requests. See https://github.com/dotnet/aspnetcore/issues/34541 for more info.

**Comment by tdashworth** [comment]
@alexalok Thanks so much for getting back!
