### ISSUE TITLE
[Question] The future of Carter

### ISSUE THREAD

**Issue by lewisrenfrew** [CarterCommunity/Carter#325]
Hello - I hope this is an acceptable way to ask a question - if not just delete/ignore.

Firstly, thanks for all your work on Carter (and Nancy for that matter)! Been using both happily for years and the experience has been great.

I was just wondering what the future of Carter looks like, if such a question has some kind of answer? I start new projects fairly regularly and every time I am faced with the choice of sticking with Carter, or trying out the vanilla .NET Core stuff, particularly the minimal API approach.

As dotnet races through major versions, I would ideally like to know if the plan is to continue to develop Carter in tandem, or slowly phase it out as microsoft slowly adds all the features that Carter pioneers (particularly for me: the module discovery and content/response negotiation implementations in Carter are excellent  and I'd be sad to lose them... although I am keen to keep up with latest dotnet versions when starting new apps for obvious reasons).

If the future is unclear or you haven't really thought about it yet then apologies for jumping the gun!

Thanks again,

Lewis

**Comment by jchannon** [comment]
Hi

I think at this stage it's down to you the user to decide if you want to
continue.

As you say MS keeps adding stuff to MinimalAPI that Carter/Nancy originally
had. At the moment the grouping and the response negotiation and built in
validation is the USP for Carter. The grouping I don't think MS will do
much with as you can easily add extension methods in ASP.NET Core to
simulate Carter modules. It's just whether you want to write those
extensions yourself.

I'm not going to stop Carter, I'm just not sure if I will add any new
features currently but that's just because I think it's stable and I can't
think of any new features required!

Hope that helps a little
