### ISSUE TITLE
Error On Register IN DI 

### ISSUE THREAD

**Issue by Mubark-p** [CarterCommunity/Carter#328]
System.AggregateException: 'Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Carter.IValidatorLocator Lifetime: Singleton ImplementationType: Carter.DefaultValidatorLocator': Cannot consume scoped service 'System.Collections.Generic.IEnumerable`1[FluentValidation.IValidator]' from singleton 'Carter.IValidatorLocator'.)'

**Comment by crodriguesbr** [comment]
@Mubark-p Test with the new version.

**Comment by koniecdev** [comment]
Can You explain how? @crodriguesbr Probably because Carter, my FluentValidation is not working. https://github.com/FluentValidation/FluentValidation/issues/2183

carter.ivalidatorlocator lifetime: singleton implementationtype: carter.defaultvalidatorlocator': cannot consume scoped service 'savethekitty.api.databases.interfaces.imaindbcontext' from singleton 'fluentvalidation.ivalidator'.

**Comment by crodriguesbr** [comment]
@koniecdev A service registered as a singleton cannot invoke a service registered as scoped, which is why a way of defining how validators would be registered was implemented in Carter.

`  services.AddCarter(configurator: cfg =>
         {
             cfg.WithValidatorLifetime(ServiceLifetime.Scoped);
         });`

I hope it resolves.

**Comment by koniecdev** [comment]
It worked @crodriguesbr . Thank You. I kinda wonder why is this not default ngl.

**Comment by crodriguesbr** [comment]
@koniecdev As Carter already registered validators as singletons, we decided to keep them registered by default to avoid code breakage. Still, we left the developer the option to change this.
