### ISSUE TITLE
Package conflict with Microsoft.EntityFrameworkCore.Design 9.0.0

### ISSUE THREAD

**Issue by Denny09310** [CarterCommunity/Carter#369]
When I try to install the package `Microsoft.EntityFrameworkCore.Design` with version `9.0.0` it gives me this error:

```
A version conflict was detected for Microsoft.CodeAnalysis.Common. To resolve this issue, install Microsoft.CodeAnalysis.Common 4.11.0 or reference it directly in your BlazorApp1 project. 
 BlazorApp1 -> Microsoft.EntityFrameworkCore.Design 9.0.0 -> Microsoft.CodeAnalysis.CSharp 4.11.0 -> Microsoft.CodeAnalysis.Common (= 4.11.0) 
 BlazorApp1 -> Microsoft.EntityFrameworkCore.Design 9.0.0 -> Microsoft.CodeAnalysis.CSharp.Workspaces 4.8.0 -> Microsoft.CodeAnalysis.Common (= 4.8.0).
```

If I install the package `Microsoft.CodeAnalysis.Common` separately with the latest version then it does not complain, until I try to run a migration for example. Then the tool gives another exception not finding the correct properties inside the assembly `Microsoft.CodeAnalysis.CSharp 4.11.0`. Is this a EntityFrameworkCore problem and I need to file an issue for them? Or there is a fater way to solve this?

**Comment by jchannon** [comment]
I think the issues is them. Carter is using the latest Microsoft.CodeAnalysis.CSharp 4.11.0

**Comment by Denny09310** [comment]
Yes, I've seen a very similar issue on their github. They said that they'll not fix this. Only solution is to downgrade to 8.2.1, no problem.

**Comment by hades200082** [comment]
EF Core git issue - https://github.com/dotnet/efcore/issues/33970

**Comment by mikesigs** [comment]
@jchannon The EFCore team is adamant that they aren't going to update the version of CodeAnalysis they're using. The linked issue above goes into greater detail why. IIUC the CodeAnalysis version is tightly coupled to the version of Visual Studio, and if they update the version then they'll be breaking a bunch of folks still on VS2019. So, unless there is some critical feature that Carter requires from the latest version of CodeAnalysis, you might consider lowering the version constraint in Carter. Otherwise, I think this issue will plague many of your users until EF 10 is released with .NET 10.

**Comment by jchannon** [comment]
@mikesigs @hades200082 @Denny09310 please read this and a feedz nuget feed and install version `Carter.9.0.1-alpha.0.2.nupkg` - I have downgraded the CodeAnalysis version

**Comment by jchannon** [comment]
There is a .NET 10 build with EF Core if you want to pull the code and run the sample - https://github.com/CarterCommunity/Carter/tree/net10/samples/EntityFwk
